### ISSUE TITLE
Visual Studio Project Build Fail

### ISSUE THREAD

**Issue by wulcat** [ThePhysicsGuys/Physics3D#12]
Installed packages from vcpkg like _glfw.h_ are not referenced in Visual Studio Project. Hence the build is failing using current _.sln_.

To reproduce-
1) Clone the project
2) Run installation setups from the Readme.md
3) Run command./vcpkg integrate install
4) Reopen project sln in Visual Studio 2019 
5) Build x86 Debug

Few errors for missing headers
- Error C1083 Cannot open include file: 'core.h': No such file or directory application _Physics3D\application\picker\ray.cpp_
- Error (active) E1696 cannot open source file "GLFW/glfw3.h" graphics _Physics3D\include\imgui\imgui_impl_glfw.cpp_

**Comment by VonTum** [comment]
The manual setup for visual studio, vs the automatic setup with CMake and vcpkg are different. 

It's a bit wonky at the moment, but for visual studio you have to download the libraries manually. There are download links to all of them with the versions we use ourselves noted in the README. If you want I can also just post a download link with a zip of our include/ and lib/ folders. 

Another option is to use cmake, where you just have to run install/setup.bat, though you won't be able to use visual studio with that.

**Comment by VonTum** [comment]
Perhaps we should migrate the visual studio process to use CMake as well, although I do fear we'll lose some of the customizability that a native .sln offers

**Comment by wulcat** [comment]
Commenting out ecsTest.cpp and fixing typo from CMakeLists I was able to build successfully using CMake. Still stuck with Visual Studio. Thanks.

**Comment by VonTum** [comment]
Yeah, I have the noncompiling test commented out as well, it refers to some code that hasn't been committed yet. For the visual studio build, here are my lib/ and include/ folders
https://we.tl/t-igLviOLFoi

If you want to mess around with it, the controls are listed in res/.properties, they're currently set for AZERTY keyboards but you can change them in .properties
As for the world, application.cpp:138 (setupWorld) is where the world is built, it's currently a fairly simple world, but you can look at the showcase world by incommenting line 144 `buildShowcaseWorld(screen, world); return;`
There's also `WorldBuilder::buildTerrain(100, 100)` for terrain

**Comment by VonTum** [comment]
The CMake build has now been fixed :partying_face:
