### ISSUE TITLE
can't launch application.exe

### ISSUE THREAD

**Issue by EpicSpaces** [ThePhysicsGuys/Physics3D#16]
in the file tickerthread.h line 19 there is something wrong when launching from Visual Studio 
it's killing me, launching the exe either debug/release x64 from folder nothing happens .

link to the error
https://imgur.com/u4yH7Cz

so any help, or should I abandon, struggling.

**Comment by VonTum** [comment]
What kind of CPU are you using? Visual Studio compiles for SSE2-compatible CPUs by default, and it seems yours does not have SSE2. 

You can have visual studio compile for base x86 by right-clicking every project in turn, selecting 'Properties', and in there setting C++ > Code Generation > Enable Enhanced Instruction Set => To "No Enhanced Instructions (/arch:IA32)"

Let me know if that fixes it :)

**Comment by EpicSpaces** [comment]
:) thanks bro

**Comment by VonTum** [comment]
Fantastic 😄 

I'll look into making that the default, if it doesn't affect performance too much.
