### ISSUE TITLE
Build fail on Zorin OS [`explicit specialization in non-namespace scope`]

### ISSUE THREAD

**Issue by tree786isback** [ThePhysicsGuys/Physics3D#17]
**Describe the bug**
I'm trying to build the `application` demo on Zorin. After executing the setup shell script, I tried to build using `make -j`, but I get these errors related to the ECS:
```
In file included from /home/mm/Desktop/Physics3D/benchmarks/ecsBenchmark.cpp:2:
/home/mm/Desktop/Physics3D/benchmarks/../engine/ecs/registry.h:207:13: error: explicit specialization in non-namespace scope ‘struct P3D::Engine::Registry<Entity>::only<Component>’
  207 |   template <>
      |             ^

```
Any ideas how to fix this?

**To Reproduce**
1. git clone recursive
2. follow build instructions [here](https://github.com/ThePhysicsGuys/Physics3D#ubuntu-specific-using-apt-get)
3. enter build folder and run `make -j`
4. Error

**Expected behavior**
Expected to build

**Screenshots**
-

**Additional context**
GCC v 9.3.0

**Comment by olympus112** [comment]
I fixed the bug in the latest commit. MSVC and Clang are sometimes non-compliant to the standard: they allow the specialization of templates in non-namespace scopes, while GCC does not. You can find a good explanation here: https://stackoverflow.com/questions/3052579/explicit-specialization-in-non-namespace-scope.

**Comment by tree786isback** [comment]
Thanks  !
It compiles better now, reaching almost 100%, but it now fails at a different [spot](https://github.com/ThePhysicsGuys/Physics3D/blob/f3ce30379c898a74ba6fa137b3e5d2012558406c/application/builtinWorlds.cpp#L447):

```
/home/mm/Desktop/Physics3D/application/builtinWorlds.cpp:447:74: error: no matching function for call to ‘registerShape(P3D::Graphics::ExtendedTriangleMesh*)’
  447 |         Graphics::Comp::Mesh mesh = Graphics::MeshRegistry::registerShape(ball->getShape());

```

**Comment by olympus112** [comment]
Ah that was my mistake, I still had some uncommitted changes on my machine. It should be fixed now.

**Comment by tree786isback** [comment]
Thanks very much!
I was interested in using the renderer/graphics part of P3D in some of my projects, as it already has some out-of-the box features like alpha support and shadows. Would it be ok if I ask Q's in the issue's section? Or is there a dedicated forum/thread which I can use?

**Comment by olympus112** [comment]
For the moment, we don't have anything like that set up. But we can invite you to our Discord if would like to ask some questions.

As for using the renderer: it's true that a lot of features have been implemented, but this has been a sort of learning project for me, so not every feature is as polished as it could be. Some features, such as shadows for example, are due for a major rewrite. If you have no problem with that, i would be glad to answer your questions.

**Comment by olympus112** [comment]
Awesome, I will need your Discord username though 😛.

**Comment by tree786isback** [comment]
`tree786#3873` :)
