### ISSUE TITLE
Make a video guide for installing physics3d

### ISSUE THREAD

**Issue by dontmansion1984** [ThePhysicsGuys/Physics3D#27]
I can't get how to install physics3d. Video can help to.

**Comment by VonTum** [comment]
Sorry, we're no longer maintaining Physics3D. While I enjoy working on it, it doesn't really lead to a future for either me or Olympus. 

The instructions in the README should be quite clear though, what OS are you trying to run them on and where are you getting stuck? 

Though, given the project is in C++ with CMake, it's quite likely things tend to break over time just as a result of this platform.
